---
title: "PCA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("XXX")

library("devtools")
library("factoextra")
library("RColorBrewer")
library("pheatmap")
library("gplots")
library("d3heatmap")
```

```{r}
inputfile <- read.csv('PCA.csv', header = TRUE)
dr <- data.frame(inputfile)
matrix <- dr[ ,-(1:6)]
```

Deciding the number of dimensions
```{r}
res.pca <- prcomp(matrix, scale = TRUE)
summary(res.pca)
```

Deciding the number of dimensions
```{r}
fviz_eig(res.pca)
```
PCA scatter plot of the samples
```{r}
fviz_pca_ind(res.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```
## Graph of variables
```{r}
fviz_pca_var(res.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```

# plot of both the samples and variables
```{r}
fviz_pca_biplot(res.pca, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )
```

## 3 group distribution with elliptical boundaries based on confidence
```{r}
groups <- as.factor(dr$Distribution)
fviz_pca_ind(res.pca,
             col.ind = groups, # color by groups
             palette = c("#00AFBB",  "#FC4E07", "#E7B800"),
             
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "confidence",
             legend.title = "Groups",
             repel = TRUE, 
             label = "all"
             )
```

H. clustering - dendrogram and heatmap 
```{r}

res.hc <- hclust(dist(matrix),  method = "ward.D2")
fviz_dend(res.hc, cex = 0.5, k = 4, palette = "jco") 
heatmap.2((t(as.matrix(matrix))), cexCol = "0.5", cexRow = "0.5", margins = c(1,1), labCol = dr$Distribution, col = colorRampPalette(brewer.pal(8, "PiYG")), Colv = NA, trace = "none")

```


```{r}
fviz_dend(res.hc, cex = 0.5, k = 4, palette = "jco") 
heatmap((t(as.matrix(matrix))), cexCol = "0.5", cexRow = "0.5", margins = c(1,1), labCol = dr$Distribution, col = colorRampPalette(brewer.pal(8, "PiYG"))(25), Colv = NA, )
```
